name: Build and Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint
      run: |
        black . --check
        isort . --check
        pyflakes .
    - name: Test with pytest
      # Run all tests except the end_to_end test, which doesn't work in Github Actions.
      run: |
        pytest -k 'not end_to_end'
