name: Build and Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint
      run: |
        black . --check
        isort . --check
        pyflakes .
    - name: Test with pytest
      # TODO: run the tests in the other packages as well. Also figure out
      #   how to run the end_to_end test in Github Actions.
      run: |
        pytest stefan-on-software
